### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by ashterenli** [Portals4/portals4#85]
I'm trying to find the specs, but hit lots of dead links:

- on this page - http://www.cs.sandia.gov/Portals/portals4.html - dead

- on parent page - http://portals4.org - dead

- On Sandia pages: https://cfwebprod.sandia.gov/cfdocs/CompResearch/templates/insert/softwre.cfm?sw=29 - both links are dead - "[Software website](http://www.cs.sandia.gov/Portals/) | [Software downloads](http://www.cs.sandia.gov/Portals/portals4-impl.html)"

- These 2 links work, but not sure how up to date this is:
- https://cs.sandia.gov/Portals/portals4.html
- https://cs.sandia.gov/Portals/portals4-spec.html

**Comment by tkordenbrock** [comment]
@ashterenli Thanks for reporting the problem.  Can you try the three `www.cs.sandia.gov` links without the leading `www.`.  That is:
* http://cs.sandia.gov/Portals/portals4.html
* http://cs.sandia.gov/Portals/
* http://cs.sandia.gov/Portals/portals4-impl.html

I think we had a DNS change and the leading `www.` is no longer required or allowed.

I will look into the portals4.org situation.


> I'm trying to find the specs, but hit lots of dead links:
> 
>     * on this page - http://www.cs.sandia.gov/Portals/portals4.html - dead
> 
>     * on parent page - http://portals4.org - dead
> 
>     * On Sandia pages: https://cfwebprod.sandia.gov/cfdocs/CompResearch/templates/insert/softwre.cfm?sw=29 - both links are dead - "[Software website](http://www.cs.sandia.gov/Portals/) | [Software downloads](http://www.cs.sandia.gov/Portals/portals4-impl.html)"
> 
>     * These 2 links work, but not sure how up to date this is:
> 
>     * https://cs.sandia.gov/Portals/portals4.html
> 
>     * https://cs.sandia.gov/Portals/portals4-spec.html

**Comment by whit-schonbein** [comment]
I'm looking into the Sandia-hosted pages. The powers that be have been migrating pages around and obviously something went awry.

**Comment by whit-schonbein** [comment]
It looks like they migrated the pages but failed to fully remove the old pages. The new Portals site is:

https://www.sandia.gov/portals/

I've updated the link in the GitHub `About' section.

**Comment by ashterenli** [comment]
Thank you. The most up-to-date page is still

https://cs.sandia.gov/Portals/portals4-spec.html

If there is nothing newer, please close this ticket.

**Comment by tkordenbrock** [comment]
The info on https://cs.sandia.gov/Portals/portals4-spec.html is the most current, but a nicer formatting of that info is available at https://www.sandia.gov/portals/portals-4-0-specification/.  The page that @whit-schonbein mentioned has links to that and all the other Portals4 info.

**Comment by whit-schonbein** [comment]
Also, the old links will at some point redirect to the new pages. Thank you @ashterenli for raising issue.
